### ISSUE TITLE
在docker伺服里无法正确创建按钮

### ISSUE THREAD

**Issue by Tlonglan** [muhanstudio/siyuan-widget-Button#2]
如图，点击提交之后一直卡在这个按钮样式中，无法正确生成按钮，点击按钮也没有反应

![image](https://github.com/muhanstudio/siyuan-widget-Button/assets/38731172/62a6ff5d-70a3-4bec-9c70-c42178a777ad)

**Comment by muhanstudio** [comment]
按钮已经生成了，调整挂件大小为你想要的尺度就可以了，如果没有反应，可以shift+ctrl+i打开控制台看看输出，多半是写的代码有问题，代码内容也可以看一下
